### ISSUE TITLE
Getting "Unexpected usage" in console

### ISSUE THREAD

**Issue by danieleff** [Microsoft/monaco-editor-webpack-plugin#32]
After creating a new project:
`npm init`
`npm install --save webpack monaco-editor monaco-editor-webpack-plugin style-loader css-loader`
```
+ monaco-editor@0.14.3
+ monaco-editor-webpack-plugin@1.5.2
+ webpack@4.17.1
+ style-loader@0.23.0
+ css-loader@1.0.0
```

If I run the example code from the main page, I get the following in the browser console:
```
Error: Unexpected usage
    at EditorSimpleWorkerImpl.BaseEditorSimpleWorker.loadForeignModule (editorSimpleWorker.js:407)
    at eval (webWorker.js:42)
    at ShallowCancelThenPromise.CompletePromise_then [as then] (winjs.base.js:1591)
    at MonacoWebWorkerImpl._getForeignProxy (webWorker.js:41)
    at MonacoWebWorkerImpl.getProxy (webWorker.js:65)
    at WorkerManager._getClient (workerManager.js:55)
    at WorkerManager.getLanguageServiceWorker (workerManager.js:74)
    at DiagnostcsAdapter.worker [as _worker] (tsMode.js:46)
    at DiagnostcsAdapter._doValidate (languageFeatures.js:158)
    at onModelAdd (languageFeatures.js:117)
```

the editor appears, and typing works, but after every keypress I get:

```
Error: Unexpected usage
    at EditorSimpleWorkerImpl.BaseEditorSimpleWorker.loadForeignModule (editorSimpleWorker.js:407)
    at eval (webWorker.js:42)
    at ShallowCancelThenPromise.CompletePromise_then [as then] (winjs.base.js:1591)
    at MonacoWebWorkerImpl._getForeignProxy (webWorker.js:41)
    at MonacoWebWorkerImpl.getProxy (webWorker.js:65)
    at WorkerManager._getClient (workerManager.js:55)
    at WorkerManager.getLanguageServiceWorker (workerManager.js:74)
    at SuggestAdapter.worker [as _worker] (tsMode.js:46)
    at SuggestAdapter.provideCompletionItems (languageFeatures.js:216)
    at SuggestAdapter.provideCompletionItems (standaloneLanguages.js:482)
    at EditorSimpleWorkerImpl.BaseEditorSimpleWorker.loadForeignModule (editorSimpleWorker.js:407)
    at eval (webWorker.js:42)
    at ShallowCancelThenPromise.CompletePromise_then [as then] (winjs.base.js:1591)
    at MonacoWebWorkerImpl._getForeignProxy (webWorker.js:41)
    at MonacoWebWorkerImpl.getProxy (webWorker.js:65)
    at WorkerManager._getClient (workerManager.js:55)
    at WorkerManager.getLanguageServiceWorker (workerManager.js:74)
    at SuggestAdapter.worker [as _worker] (tsMode.js:46)
    at SuggestAdapter.provideCompletionItems (languageFeatures.js:216)
    at SuggestAdapter.provideCompletionItems (standaloneLanguages.js:482)
```

If I change `language: 'javascript'` to `c`, `java`, there are no errors on console (and coloring works). `json`, `javascript`, `typescript` gives the error (coloring kind of works. some keywords are colored).

In `webpack.config.js` it is `new MonacoWebpackPlugin()`

**Comment by Canna71** [comment]
I have the same issue. For what I can tell, the reason is that
_foreignModuleFactory is null in BaseEditorSimpleWorker, but this is because the _getOrCreateWorker method fails with
"You must define a function MonacoEnvironment.getWorkerUrl or MonacoEnvironment.getWorker"
which, as I understand, is what MonacoWebpacPlugin should do behind the scenes.
I'll try with the "manual" approach explained [here](https://github.com/Microsoft/monaco-editor/blob/master/docs/integrate-esm.md#option-2-using-plain-webpack)

**Comment by Sibiraj-S** [comment]
I had the same issue, but I resolved it. I can help if you provide a minimal reproduction of the issue, a github repo will be nice. I will try to help

**Comment by Sibiraj-S** [comment]
For Javascript

My Webpack configuration is 

 ```
new MonacoWebpackPlugin({
      languages: ['javascript', 'typescript']
 })
```

Which fixed my issue.

**Comment by arieldf** [comment]
@Canna71 @danieleff I am experiencing the same issue and have not been able to resolve it yet. Did you manage to get it to work? I will share any progress I make here.

**Comment by leonieponsioen** [comment]
Same issue here after upgrading to 1.5.2, temporarily solved this by downgrading to 1.5.1 @arieldf

**Comment by alexandrudima** [comment]
Are you on Windows? #33 should help.

**Comment by alexandrudima** [comment]
I have published 1.5.3 with the regex fix for windows.

**Comment by danieleff** [comment]
> 
> 
> I have published 1.5.3 with the regex fix for windows.

I confirm that this works for me, no longer getting the error messages.

**Comment by paulyoung** [comment]
I'm seeing this using the manual approach. json and javascript have issues but java is fine (for example)

@alexandrudima, any suggestions on what might be going wrong?

**Comment by paulyoung** [comment]
From reading something online, I think perhaps I just needed to do the following but I haven't tried it out yet.

```
import * as editor from 'monaco-editor/esm/vs/editor/editor.main';
```

**Comment by ktalebian** [comment]
I'm getting the same error, and adding `languages: ['javascript', 'typescript']` does NOT solve the problem.

**Comment by lolleko** [comment]
I was launching my application by opening a `index.html` file in a browser and did get the same exception. After that I tried running it on a web server and that solved the issue.

The fact that `file:///` is not supported, is mentioned in the FAQ of the main Monaco repo (https://github.com/Microsoft/monaco-editor#faq).
But It might be worth mentioning that fact in the README of this repo as well, because it's especially tempting to launch via file:/// when using webpack and
```
Error: Unexpected usage
...
```
is not really a descriptive error.

**Comment by lichenhao** [comment]
Same problem and not work for me now 
System Macos and latest version for me.

**Comment by TLadd** [comment]
@lichenhao I was having the same issue today. Found out from https://github.com/Microsoft/monaco-editor-webpack-plugin/issues/27 that including only "javascript" in the languages option for the plugin won't work, and you also have to include "typescript". Not sure what your config looks like, but might be your issue if you're trying to only use "javascript".

**Comment by NervosaX** [comment]
My config looks like:

```javascript
		new MonacoWebpackPlugin({
			languages: ["javascript", "typescript", "html", "json"]
		})
```

But I still get this error.

**Comment by Drau** [comment]
Im actually getting the same error without even using the plugin !
So maybe its really a monaco-editor issue ?

Im using react-monaco-editor with nextjs

**Comment by masad-frost** [comment]
I noticed that these errors might be misleading misleading, the problem is usually in the worker itself. Try to find other errors if any in the worker and work from there. In my case the css worker fails and gives this error because of this issue https://github.com/Microsoft/monaco-editor/issues/1169

**Comment by naprimer18** [comment]
I use React-monaco-editor with a webpack. And I get this error.
![image](https://user-images.githubusercontent.com/33267979/48848155-1c26a600-ed58-11e8-9c16-6aea9847fd63.png)
![image](https://user-images.githubusercontent.com/33267979/48848187-2fd20c80-ed58-11e8-8990-62a7bf2dba5f.png)

**Comment by paranoidjk** [comment]
Same Problem here

**Comment by wxg3a702** [comment]
> **j**

i have same issue, are you solve it?

**Comment by wxg3a702** [comment]
> Im actually getting the same error without even using the plugin !
> So maybe its really a monaco-editor issue ?
> 
> **c / java** works
> **json / xml / js** works with the said errors in console.
> 
> Im using **react-monaco-editor** with **nextjs**

i have same issue, are you solve it?

**Comment by Evanfeenstra** [comment]
@drau @wxg3a702  I solved this issue with Nextjs like this:
```
import MonacoEditor from 'react-monaco-editor'
import '../node_modules/monaco-editor/min/vs/editor/editor.main.css'
window.MonacoEnvironment = { 
    getWorkerUrl: function (moduleId, label) {
      if (label === 'json') return 'static/monaco/json.worker.js';
      if (label === 'css') return 'static/monaco/css.worker.js';
      if (label === 'html') return 'static/monaco/html.worker.js';
      if (label === 'typescript' || label === 'javascript') return 'static/monaco/typescript.worker.js';
      return 'static/monaco/editor.worker.js';
    }
};
```
And my next.config.js looks like:
```
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');
module.exports = {
  webpack: (config) => {
    config.node = {
      fs: 'empty'
    }
    config.module.rules.push(
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader']
      },
      {
        test: /\.worker\.js$/,
        use: { 
          loader: 'worker-loader',
          options: { inline: true }
        }
      }
    )
    config.plugins.push(
      new MonacoWebpackPlugin({
        languages: ['javascript','typescript','css','html','json']
      })
    )
    return config
  }
}
```

**Comment by trey-miller** [comment]
Similar to @Evanfeenstra 's solution, I found a solution to this problem after reviewing the main monaco-editor's page on [integration with the ESM version](https://github.com/Microsoft/monaco-editor/blob/master/docs/integrate-esm.md) and saw that the non-plugin way included setting the window.MonacoEnvironment. So for me with a webpack config having the output filename as `[name].bundle.js`, I added this code before insantiating the editor, and the issue went away: 
```typescript
(window as any).MonacoEnvironment = {
    getWorkerUrl: function (moduleId: string, label: string) {
        if (label === 'json') {
            return './json.worker.bundle.js';
        }
        if (label === 'css') {
            return './css.worker.bundle.js';
        }
        if (label === 'html') {
            return './html.worker.bundle.js';
        }
        if (label === 'typescript' || label === 'javascript') {
            return './ts.worker.bundle.js';
        }
        return './editor.worker.bundle.js';
    }
};
```

**Comment by astephens** [comment]
I spent a while trying to fix this issue and ended up having to define both getWorkUrl and getWorker:

```
window.MonacoEnvironment = {
	getWorkerUrl: function (moduleId, label) {
		if (label === 'json')
			return '/json.worker.js';
		if (label === 'css')
			return '/workers/css.worker.js';
		if (label === 'html')
			return '/html.worker.js';
		if (label === 'typescript' || label === 'javascript')
			return '/typescript.worker.js';

		return '/editor.worker.js';
	},
	getWorker: function (moduleId, label) {
		if (label === 'json')
			return new Worker('./workers/json.worker.js');
		if (label === 'css')
			return new Worker('./workers/css.worker.js');
		if (label === 'html')
			return new Worker('./workers/html.worker.js');
		if (label === 'typescript' || label === 'javascript')
			return new Worker('./workers/ts.worker.js');

		return new Worker('./workers/editor.worker.js');
	}
};
```

**Comment by Aralhi** [comment]
Why this issue is closed? i have the same issue
// webpack.config.js
```
new MonacoWebpackPlugin()
```
and language is javascript
OS is mac
```
Error: Unexpected usage
    at EditorSimpleWorkerImpl.push../client/node_modules/_monaco-editor@0.16.1@monaco-editor/esm/vs/editor/common/services/editorSimpleWorker.js.BaseEditorSimpleWorker.loadForeignModule (editorSimpleWorker.js:470)
    at webWorker.js:39
```

**Comment by trey-miller** [comment]
My end solution ended up being basically this, where I had to deal with a few things:
1. monaco-editor-webpack-plugin creates a version of editor.main.js that overwrites MonacoEnvironment when `monaco-editor/esm/vs/editor/editor.api` is imported, so I had to import it first and then overwrite.
2. I had to have the possibility of running from anywhere (e.g. a cdn) so I used the EnvironmentPlugin to get the WEBPACK_PUBLIC_PATH.
3. Because of the public path problem, I also had to make the `MonacoEnvironment.getWorkerUrl` return a data URI instead of a real file path.
```typescript
await import('monaco-editor/esm/vs/editor/editor.api');

const publicPath = process.env.WEBPACK_PUBLIC_PATH;
function getWorkerUrl(workerId: string, label: string) {
    switch (label) {
        case 'json':
            return publicPath + 'json.worker.js';
        case 'css':
        case 'less':
        case 'scss':
            return publicPath + 'css.worker.js';
        case 'html':
        case 'handlebars':
        case 'razor':
            return publicPath + 'html.worker.js';
        case 'javascript':
        case 'typescript':
            return publicPath + 'typescript.worker.js';
        default:
            return publicPath + 'editor.worker.js';
    }
}

(window as any).MonacoEnvironment = {
    getWorkerUrl: function (workerId, label) {
        const url = getWorkerUrl(workerId, label);
        return `data:text/javascript;charset=utf-8,${encodeURIComponent(`                        
                    self.MonacoEnvironment = {
                      baseUrl: '${publicPath}'
                    };
                    importScripts('${url}');`
        )}`;
    }
};
```
I'm using monaco-editor@0.15.6, and monaco-editor-webpack-plugin@1.7.0, if that makes any difference.

**Comment by tomerry** [comment]
i solved this by 
modify node_modules/monaco-editor/esm/vs/language/json/_deps/vscode-json-languageservice/jsonLanguageService.js

`//export { TextDocument, Position, CompletionItem, CompletionList, Hover, Range, SymbolInformation, Diagnostic, TextEdit, FormattingOptions, MarkedString };
`

maybe there would be some new question ,but it runs

**Comment by felipap** [comment]
@tomerry This didn't work for me, unfortunately. Did you have to take any extra steps?

**Comment by ThanrayTian** [comment]
I load monaco-editor from a cdn asyncronously, and it works.
[https://github.com/leo-buneev/vue-monaco-cdn/blob/master/src/services/monaco-loader.js](url)

**Comment by simerlec** [comment]
What helped in our case was removing the deprecated UglifyJS plugin for webpack and replacing it with the TerserWebpackPlugin. Now I'm running into #85 for which I have no solution yet.
